 vim.api.nvim_set_keymap('x', '<S-C>', ':"<,"<w !xclip -selection clipboard<CR>', { noremap = true })
 vim.api.nvim_set_keymap('n', '<C-m>', ':tabn<cr>', { noremap = true })
 vim.api.nvim_set_keymap('n', '<C-t>', ':tabnew<cr>', { noremap = true })
 vim.api.nvim_set_keymap('n', '<C-p>', ':TerminalSplit bash<CR>', { noremap = true })
 vim.api.nvim_set_keymap('n', '<C-w>', ':tabc<cr>', { noremap = true })
 vim.api.nvim_set_keymap('n', '<C-h>', '<C-w>h', { noremap = true })
 vim.api.nvim_set_keymap('n', '<C-j>', '<C-w>j', { noremap = true })
 vim.api.nvim_set_keymap('n', '<C-k>', '<C-w>k', { noremap = true })
 vim.api.nvim_set_keymap('n', '<C-l>', '<C-w>l', { noremap = true })
 vim.api.nvim_set_keymap('i', '<cr>', '"<c-g>u<CR>"', { noremap = true, silent = true, expr = true })
 vim.api.nvim_set_keymap('n', '<S-k>', '<Nop>', { noremap = true })
 vim.api.nvim_set_keymap('n', 'q', '<Nop>', { noremap = true })
